# Generated by Django 3.2.5 on 2021-08-03 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_death', models.TextField(blank=True, null=True)),
                ('pre_live', models.TextField(blank=True, null=True)),
                ('payment_from_contract', models.FloatField(blank=True, null=True)),
                ('monthly_payment', models.FloatField(blank=True, null=True)),
                ('tariff', models.FloatField(blank=True, null=True)),
                ('jurnal_register_number', models.TextField(blank=True, null=True)),
                ('register_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Class_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='', null=True)),
                ('code', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company_branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oked', models.IntegerField(blank=True, null=True)),
                ('activity_type', models.TextField(blank=True, null=True)),
                ('summa_by_contract', models.FloatField(blank=True, null=True)),
                ('tariff', models.FloatField(blank=True, null=True)),
                ('jurnal_register_number', models.TextField(blank=True, null=True)),
                ('register_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('act_start_date', models.DateField(blank=True, null=True)),
                ('act_finish_date', models.DateField(blank=True, null=True)),
                ('reference', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('insurer', models.BooleanField(default=False)),
                ('access_contract_type', models.CharField(blank=True, choices=[('only_yours', 'только своим'), ('subdivision', 'подразделение'), ('branches', 'филиалы'), ('all_branches', 'всех филиалов')], max_length=128, null=True)),
                ('access_permission_type', models.CharField(blank=True, choices=[('create_update', 'Cоздание/редактирование договора '), ('only_read', 'Только для читение '), ('only_read_own_create', 'Только для читение/созд.своих ')], max_length=128, null=True)),
                ('pretense', models.BooleanField(default=False)),
                ('library', models.BooleanField(default=False)),
                ('update_news', models.BooleanField(default=False)),
                ('checking', models.CharField(blank=True, choices=[('no', 'Нет'), ('user', 'Пользователь'), ('administrator', 'Администратор')], max_length=128, null=True)),
                ('import_data', models.BooleanField(default=False)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('fath_name', models.TextField(blank=True, null=True)),
                ('date_birth', models.DateField(blank=True, null=True)),
                ('passport_serial', models.CharField(blank=True, max_length=9, null=True)),
                ('given_date', models.DateField(blank=True, null=True)),
                ('issue_place', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
                ('company_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company_branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.TextField(blank=True, null=True)),
                ('passport_given', models.DateField(blank=True, null=True)),
                ('given_date', models.DateField(blank=True, null=True)),
                ('inps', models.TextField(blank=True, null=True)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('fath_name', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('1', 'мужчина'), ('2', 'женщина')], max_length=128, null=True)),
                ('date_birth', models.DateField(blank=True, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('chp', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oked', models.IntegerField(blank=True, null=True)),
                ('activity_type', models.TextField(blank=True, null=True)),
                ('summa_by_contract', models.FloatField(blank=True, null=True)),
                ('tariff', models.FloatField(blank=True, null=True)),
                ('jurnal_register_number', models.TextField(blank=True, null=True)),
                ('register_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Okonx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Polis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_by_contract', models.FloatField(blank=True, null=True)),
                ('year_rent_sum', models.IntegerField(blank=True, null=True)),
                ('rent_till60', models.DateField(blank=True, null=True)),
                ('n1', models.FloatField(blank=True, null=True)),
                ('n2', models.FloatField(blank=True, null=True)),
                ('rent2_till60', models.DateField(blank=True, null=True)),
                ('premium', models.FloatField(blank=True, null=True)),
                ('start_period', models.DateField(blank=True, null=True)),
                ('jurnal_register_number', models.TextField(blank=True, null=True)),
                ('register_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rent_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('summa', models.FloatField(blank=True, null=True)),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rent')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.city')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.TextField(blank=True, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Polis_insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('polis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.polis')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('summa', models.FloatField(blank=True, null=True)),
                ('document_number', models.TextField(blank=True, null=True)),
                ('one_time', models.BooleanField(default=False)),
                ('tranche', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.portfolio')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.payment_type')),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('bonus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.bonus')),
                ('class_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.class_type')),
                ('dms', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.dms')),
                ('ns', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ns')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.portfolio')),
                ('rent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.rent')),
                ('travel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.travel')),
            ],
        ),
        migrations.CreateModel(
            name='Loyal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('okpo', models.TextField(blank=True, null=True)),
                ('soato', models.TextField(blank=True, null=True)),
                ('director', models.TextField(blank=True, null=True)),
                ('accountant', models.TextField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('bank_boolean', models.BooleanField(default=False)),
                ('okonx', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.okonx')),
            ],
        ),
        migrations.CreateModel(
            name='General_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_conclusion', models.DateField(blank=True, null=True)),
                ('start_period', models.DateField(blank=True, null=True)),
                ('finish_period', models.DateField(blank=True, null=True)),
                ('days', models.IntegerField(blank=True, default='', null=True)),
                ('currency_condition', models.TextField(blank=True, null=True)),
                ('payment_source', models.CharField(blank=True, choices=[('1', 'Собсвенные средства '), ('2', 'Бюжетные средства')], max_length=128, null=True)),
                ('export_agreement', models.BooleanField(default=False)),
                ('investment_project', models.BooleanField(default=False)),
                ('farmer', models.BooleanField(default=False)),
                ('sez', models.BooleanField(default=False)),
                ('new_client', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('class_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.class_type')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.currency')),
                ('geographic_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.city')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('region_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.region')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('1', 'ФИЗ'), ('2', 'ЮРД')], max_length=128, null=True)),
                ('resident', models.BooleanField(default=False)),
                ('street', models.TextField(blank=True, null=True)),
                ('house', models.TextField(blank=True, null=True)),
                ('apartment', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('site', models.TextField(blank=True, null=True)),
                ('postcode', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('phone2', models.TextField(blank=True, null=True)),
                ('fax', models.TextField(blank=True, null=True)),
                ('inn', models.TextField(blank=True, null=True)),
                ('bank', models.TextField(blank=True, null=True)),
                ('checking_account', models.TextField()),
                ('mfo', models.TextField(blank=True, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.city')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.district')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.portfolio')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.region')),
            ],
        ),
    ]
