# Generated by Django 3.2.5 on 2021-08-03 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='contract_number',
        ),
    ]
