# Generated by Django 3.2.5 on 2021-08-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_portfolio_contract_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='contract_num',
            field=models.TextField(blank=True, null=True),
        ),
    ]
