# Generated by Django 3.2.5 on 2021-08-03 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_general_information_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.portfolio'),
        ),
    ]
