# Generated by Django 3.2.5 on 2021-08-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_object_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_type',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='contract_num',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
